### ISSUE TITLE
Gmapping & Compiling C++ Project

### ISSUE THREAD

**Issue by aswinsarang** [StanleyInnovation/segway_v3#16]
1. Compiling C++ project onto ROS node and the steps i need to go through to configure CMake files into including the correct libraries, to where i should place the libraries?
2. Furthermore to the previous problem we had regarding SLAM Gmapping, we are still struggling to run the Gmapping demo with Velodyne VLP16. The error is the same as previously posted. What are the steps we need to follow to run Gmapping demo?

**Comment by PatrickHussey** [comment]
Are you trying to add a new ROS package? There are lots of resources on how to do this:
http://wiki.ros.org/ROS/Tutorials

You need to down project the VLP-16 3D pointcloud in the baselink frame to create a 2D laserscan message for gmapping. There are several packages available to do this.  It is fairly complicated to get setup correctly, which is why we offer the navigator elite package that has everything setup for you. I suggest you post questions relating to processing the VLP-16 point cloud on the [velodyne_ros repo](https://github.com/ros-drivers/velodyne). 

We generally only support this sensor when we have provided it as part of a fully integrated system, because there are too many variables out of our control to help. The code for the VLP-16 that we maintain is for a specific version of the sensor firmware/hardware that we include with the navigator elite package. So it may not work for you.

Closing because this is not related to the Segway RMP. Please post to velodyne_ros.
